### PR TITLE
Hacktoberfest

### PR DESCRIPTION
**Pull request by JamesHawkinss**
Just trying to get that free tshirt!

### CODE REVIEW

**Comment by RDIL** [comment]
fix conflicts

**Comment by SHARDcoder** [comment]
1. What free tshirt.
2. Those are my commits from a while back and there's a reason that they have conflicts | don't try to merge other people's commits 4 months after they're made :/

**Comment by SHARDcoder** [comment]
and that code is from one of my addons so there no point moving it here

**Comment by RDIL** [comment]
^^^^^^^^^^^^^
The free T-shirt is Hacktoberfest.

**Pull request closed without merging**
